name: build
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: checkout CubeConverter
        uses: actions/checkout@v4
        with:
          repository: EaseCation/CubeConverter
          path: CubeConverter
      - name: checkout BedrockMotion
        uses: actions/checkout@v4
        with:
          repository: EaseCation/BedrockMotion
          path: BedrockMotion
      - name: checkout BECamera
        uses: actions/checkout@v4
        with:
          repository: EaseCation/BECamera
          path: BECamera
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: publish CubeConverter to mavenLocal
        run: cd CubeConverter && chmod +x ./gradlew && ./gradlew publishToMavenLocal
      - name: publish BedrockMotion to mavenLocal
        run: cd BedrockMotion && chmod +x ./gradlew && ./gradlew publishToMavenLocal
      - name: publish BECamera to mavenLocal
        run: cd BECamera && chmod +x ./gradlew && ./gradlew publishToMavenLocal
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build all versions
        run: ./gradlew chiseledBuild
      - name: upload 1.21.5
        uses: actions/upload-artifact@v4
        with:
          name: viabedrockutility-mc1.21.5
          path: versions/1.21.5/build/libs/viabedrockutility-*[!s].jar
      - name: upload 1.21.6
        uses: actions/upload-artifact@v4
        with:
          name: viabedrockutility-mc1.21.6
          path: versions/1.21.6/build/libs/viabedrockutility-*[!s].jar
      - name: upload 1.21.7
        uses: actions/upload-artifact@v4
        with:
          name: viabedrockutility-mc1.21.7
          path: versions/1.21.7/build/libs/viabedrockutility-*[!s].jar
      - name: upload 1.21.8
        uses: actions/upload-artifact@v4
        with:
          name: viabedrockutility-mc1.21.8
          path: versions/1.21.8/build/libs/viabedrockutility-*[!s].jar
      - name: upload 1.21.9
        uses: actions/upload-artifact@v4
        with:
          name: viabedrockutility-mc1.21.9
          path: versions/1.21.9/build/libs/viabedrockutility-*[!s].jar
      - name: upload 1.21.10
        uses: actions/upload-artifact@v4
        with:
          name: viabedrockutility-mc1.21.10
          path: versions/1.21.10/build/libs/viabedrockutility-*[!s].jar
      - name: upload 1.21.11
        uses: actions/upload-artifact@v4
        with:
          name: viabedrockutility-mc1.21.11
          path: versions/1.21.11/build/libs/viabedrockutility-*[!s].jar